export const API_ROUTES = {
    baseUrl: 'https://api.peopleflow.ru/api/v1',
    register: '/users/auth/register',
    setPassword: '/users/auth/set-password',
    signIn: '/users/auth/sign-in',
    refreshToken: '/users/auth/refresh-token',
    resetPassword: '/users/auth/password-reset',
    resetPasswordConfirm: '/users/auth/password-reset-confirm',
    vacancies: '/vacancies/candidate-vacancies',
    vacanciesForRecruiter: '/vacancies/recruiter-vacancies',
    cities: '/base/cities',
    categories: '/base/vacancy-categories',
    templateOfBenefits: '/base/template-benefits',
    templateOfTasks: '/base/template-tasks',
    news: '/news/news',
    departments: '/base/departments',
    skills: '/base/skills',
    documents: '/news/documents',
    tags: '/news/tags',
    subscribe: '/news/subscribe',
    recruiterFlowSteps: '/base/recruiter-flow-steps',
    suitableVacancies: '/vacancies/suitable-vacancies',
    getAIVacancies: (vacancy_id: string) => `/vacancies/${vacancy_id}/suitable-candidates`,
    getCommentsAboutUser: (user_id: string) => `/users/${user_id}/comments`,
    recruiterFlows: (vacancy_id: string) => `/vacancies/${vacancy_id}/recruiter-flows`,
    getArticleComments: (article_id: string) => `${API_ROUTES.news}/${article_id}/comments`,
    getArticleById: (article_id: string) => `${API_ROUTES.news}/${article_id}`,
    setArticleReaction: (news_id: string) => `/news/news/${news_id}/reactions`,
    removeArticle: (article_id: string) => `${API_ROUTES.news}/${article_id}`,
    ws_chat: 'wss://ws.peopleflow.ru/connection/websocket',
};
