# Generated by Django 5.0.6 on 2024-06-23 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_vacancy_benefits_used_as_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новая'), (1, 'Активная'), (2, 'Неактивная'), (4, 'Завершенная'), (5, 'Архивная')], verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CandidateFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('step', models.IntegerField(choices=[(0, 'Отклик соискателя'), (1, 'Кандидат отобран'), (2, 'Общее собеседование'), (3, 'Ожидание согласования'), (4, 'Техническое собеседование'), (5, 'Дополнительное собеседование'), (6, 'Предложение о работе'), (7, 'Отказ'), (8, 'Удалено')], verbose_name='Шаг')),
                ('recruiter_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.recruiterflow')),
            ],
            options={
                'verbose_name': 'Флоу кандидата',
                'verbose_name_plural': 'Флоу кандидата',
                'ordering': ['-created_at'],
            },
        ),
    ]
