# Generated by Django 5.0.6 on 2024-06-22 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0009_vacancy_benefits_used_as_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('view_time', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Статистика вакансии',
                'verbose_name_plural': 'Статистика вакансий',
                'ordering': ['-created_at'],
            },
        ),
    ]
