# Generated by Django 5.0.6 on 2024-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read_by_candidate',
            field=models.BooleanField(default=False, verbose_name='Прочитано соискателем?'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read_by_recruiter',
            field=models.BooleanField(default=False, verbose_name='Прочитано рекрутером?'),
        ),
    ]
